### ISSUE TITLE
Endless loop/memory limit issue when ranges are invalid

### ISSUE THREAD

**Issue by kroky** [DrDub/php-nlgen#14]
If you run NLGen\Grammars\Availability\AvailabilityGenerator::generateAvailability with a range that has start time bigger than end time, e.g. [[16, 0], [8, 0]] the generator runs into an endless loop, eventually exhausting all available memory and dies with a fatal error. This is a user error but it will be much better for the generator to sanitize the input and return a textual error to the user to fix their ranges.
Also, it might be worth fixing the eternal loop no matter what input is sent to the generator.

**Comment by DrDub** [comment]
Thanks. Completely agree.

**Comment by DrDub** [comment]
Solved in #16
