### ISSUE TITLE
Please make available on Packagist.org

### ISSUE THREAD

**Issue by marclaporte** [DrDub/php-nlgen#4]
https://packagist.org/

Thanks!

**Comment by DrDub** [comment]
It should be available there shortly. Let me know if you have any suggestions for the packaging!

**Comment by marclaporte** [comment]
We got over 1000 installs, so I would say it was a great idea :-)
https://packagist.org/packages/nlgen/nlgen

**Comment by DrDub** [comment]
w00t!
